import { execAsync } from '../../constants/repoIngest';
import octokit from '../Octokit';
import { runSandboxCommand } from '../sandbox/sandBoxUtils';


export async function cloneRepoInSandbox(containerName: string, repoUrl: string) {
    await runSandboxCommand(containerName, `git clone ${repoUrl}`)
}

export async function createAndCheckoutBranch(containerName: string, branchName: string) {
    await runSandboxCommand(containerName, `git checkout -b ${branchName}`)
}

export async function commitChange(containerName: string, message: string) {
    await runSandboxCommand(containerName, `git config user.email "bot@ai-dev.com" && git config user.name "AI Dev Bot"`)
    await runSandboxCommand(containerName, `git add .`);
    await runSandboxCommand(containerName, `git commit -m "${message}`)
}

export async function pushBranch(containerName: string, branchName: string) {
    await runSandboxCommand(containerName, `git push origin ${branchName}`)
}

export async function applyFileChanges(containerName: string, filePath: string, content: string) {
    const base64Content = Buffer.from(content).toString('base64');

    const writeScript = `
      const fs = require('fs');
      const path = require('path');
      const target = '${filePath}';
      const content = Buffer.from('${base64Content}', 'base64');
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, content);
    `;

    await execAsync(`docker exec -i ${containerName} node -e "${writeScript.replace(/\n/g, ' ')}"`);
}

export async function createPullRequest(
    repoUrl: string,
    branchName: string,
    title?: string,
    body?: string,
    base: string = 'main'
) {
    const regex = /github\.com\/([^\/]+)\/([^\/]+?)(\.git)?$/;
    const match = repoUrl.match(regex);

    if (!match) {
        throw new Error("Invalid GitHub repository URL");
    }

    const owner = match[1];
    const repo = match[2];

    try {
        const response = await octokit.pulls.create({
            owner,
            repo,
            title: title || `Automated PR from Coding Agent - ${branchName}`,
            body: body || `This pull request was automatically generated by the Coding Agent for branch ${branchName}.`,
            head: branchName,
            base: base
        });

        return response.data.html_url;

    } catch (error: any) {
        if (error.status === 422 && error.message.includes("A pull request already exists")) {
            const existingPrs = await octokit.pulls.list({
                owner,
                repo,
                head: `${owner}:${branchName}`,
                state: 'open'
            });

            if (existingPrs.data.length > 0) {
                return existingPrs.data[0].html_url;
            }
        }

        console.error("Failed to create PR:", error.message);
        throw new Error(`GitHub API Error: ${error.message}`);
    }
}