export enum TaskStatus {
  CREATED = 'CREATED',
  UNDERSTANDING_REPO = 'UNDERSTANDING_REPO',
  AWAITING_ACTION = 'AWAITING_ACTION',
  PLANNING = 'PLANNING',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  EXECUTING = 'EXECUTING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED'
}

export enum TaskAction {
  REVIEW_PR = 'REVIEW_PR',
  FIX_ISSUE = 'FIX_ISSUE',
  PLAN_CHANGE = 'PLAN_CHANGE',
  FREE_FORM = 'FREE_FORM'
}